---
- name: Ensure package URL is defined
  include: pkg_url.yml
  when: threatstack_pkg_url is undefined

- name: Disable auditd service
  include: disable_auditd.yml
  when:
    - ansible_os_family == 'RedHat'
    - (ansible_distribution != 'Amazon' or ansible_kernel is search("\.amzn2\."))

- name: Run apt configure and install ThreatStack
  include: apt_install.yml
  when: ansible_os_family == 'Debian'

- name: Run yum configure and install ThreatStack
  include: yum_install.yml
  when: ansible_os_family == 'RedHat'

- name: Get threatstack user info
  getent:
    database: passwd
    key: threatstack

- name: Ensure threatstack user homedirectory is owned by user and mode 0750
  file:
    path: "{{ getent_passwd['threatstack'][4] }}"
    mode: '0750'
    owner: threatstack
    group: threatstack

- name: agent setup
  include: tsagent_setup.yml
  when:
    - threatstack_configure_agent == true
